### ISSUE TITLE
从项目的名称里面，就已经感觉到浓浓的不专业了

### ISSUE THREAD

**Issue by cnflyne** [tron-network/java-tron#2]
![image](https://user-images.githubusercontent.com/6804021/34168288-1d99dcd8-e51f-11e7-979e-97566a5e9170.png)

java-tron

**Comment by lucien-tronlab** [comment]
这是命名规范，你自己去看看以太坊的命名，人家也是go-ethereum, cpp-ethereum,前者是语言，后者是项目的名字，能不能你专业一点？

**Comment by gaodaweiwu123** [comment]
随便写点demo都能造币捞钱了啊

**Comment by cnflyne** [comment]
是这样的，币圈特色
